#!/usr/bin/python

import os
import stat
import struct
import time

pipename = "metronome.pipe"

if os.path.exists(pipename):
    try:
        os.remove(pipename)
    except IOError as e:
        print "Unable to delete old FIFO pipe - I/O error({0}): {1}".format(e.errno, e.strerror)

try:
    os.mkfifo(pipename)
except IOError as e:
    print "Unable to create FIFO pipe - I/O error({0}): {1}".format(e.errno, e.strerror)

fd = os.open(pipename, os.O_WRONLY)

try:
    while 1:
        print "Volume = 25%"
        os.write(fd, struct.pack('d', 0.25))
        time.sleep(1)
        print "Volume = 100%"
        os.write(fd, struct.pack('d', 1.0))
        time.sleep(1)
except OSError as e:
    if e.errno == 32: 
        print "Exception caught - deleting pipe and exiting"
        os.remove(pipename)
